apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operator-index
  namespace: openshift-marketplace 
spec:
  sourceType: grpc
  image: local-registry.caas.eazytraining.lab:5000/olm/redhat-operator-index:v4.10
  displayName: Operator Catalog
  publisher: EazyTraining
  updateStrategy:
    registryPoll: 
      interval: 30m