apiVersion: v1
data:
  htpasswd: ${HTPASSWD_SECRET}
kind: Secret
metadata:
  name: ${HTPASSWD_SECRET_NAME}
  namespace: openshift-config
type: Opaque
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: htpasswd_provider
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: ${HTPASSWD_SECRET_NAME}