apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${REGISTRY_PV_NAME}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shares/registry
    server: 192.168.110.9